config:
  backup: true
  banner: false
  create: true
  dotpath: ~/Projects/config-files
  keepdot: false
  longkey: true
dotfiles:
  f_library_preferences_org.vim.Vim_vimrc:
    src: Library/Preferences/org.vim.Vim/vimrc
    dst: ~/Library/Preferences/org.vim.Vim/vimrc
  f_config_vim_vimrc:
    src: Library/Preferences/org.vim.Vim/vimrc
    dst: ~/.config/vim/vimrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_library_preferences_re.deadc0de.dotdrop_config.yaml:
    src: Library/Preferences/re.deadc0de.dotdrop/config.yaml
    dst: ~/Library/Preferences/re.deadc0de.dotdrop/config.yaml
    link: link
  f_config_dotdrop_config.yaml:
    src: Library/Preferences/re.deadc0de.dotdrop/config.yaml
    dst: ~/.config/dotdrop/config.yaml
    link: link
  f_library_preferences_org.dystroy.broot_conf.toml:
    src: Library/Preferences/org.dystroy.broot/conf.toml
    dst: ~/Library/Preferences/org.dystroy.broot/conf.toml
  f_config_broot_conf.toml:
    src: Library/Preferences/org.dystroy.broot/conf.toml
    dst: ~/.config/broot/conf.toml
  f_etc_nixos_configuration.nix:
    src: etc/nixos/configuration.nix
    dst: /etc/nixos/configuration.nix
    link: nolink
  f_config_nixpkgs_config.nix:
    src: config/nixpkgs/config.nix
    dst: ~/.config/nixpkgs/config.nix
  f_etc_nixos_joeyt_default.nix:
    src: etc/nixos/joeyt/default.nix
    dst: /etc/nixos/joeyt/default.nix
  f_etc_nixos_joeyt_z-lua.nix:
    src: etc/nixos/joeyt/z-lua.nix
    dst: /etc/nixos/joeyt/z-lua.nix
  f_etc_nixos_joeyt_zsh.nix:
    src: etc/nixos/joeyt/zsh.nix
    dst: /etc/nixos/joeyt/zsh.nix
  f_library_preferences_net.sourceforge.zsh.zsh_zshrc:
    src: Library/Preferences/net.sourceforge.zsh.Zsh/zshrc
    dst: ~/Library/Preferences/net.sourceforge.zsh.Zsh/.zshrc
  f_library_preferences_net.sourceforge.zsh.zsh_joeys-avit.zsh-theme:
    src: Library/Preferences/net.sourceforge.zsh.Zsh/joeys-avit.zsh-theme
    dst: ~/Library/Preferences/net.sourceforge.zsh.Zsh/joeys-avit.zsh-theme
  f_config_zsh_themes_joeys-avit.zsh-theme:
    src: Library/Preferences/net.sourceforge.zsh.Zsh/joeys-avit.zsh-theme
    dst: ~/.config/zsh/themes/joeys-avit.zsh-theme
  f_library_preferences_net.sourceforge.zsh.zsh_zprofile:
    src: Library/Preferences/net.sourceforge.zsh.Zsh/zprofile
    dst: ~/Library/Preferences/net.sourceforge.zsh.Zsh/.zprofile
  f_library_preferences_com.npmjs.npm_npmrc:
    src: Library/Preferences/com.npmjs.Npm/npmrc
    dst: ~/Library/Preferences/com.npmjs.Npm/npmrc
  f_library_preferences_python_startup:
    src: Library/Preferences/python_startup
    dst: ~/Library/Preferences/python_startup
  f_config_ripgreprc:
    src: config/ripgreprc
    dst: ~/.config/ripgreprc
  f_config_micro_settings.json:
    src: config/micro/settings.json
    dst: ~/.config/micro/settings.json
profiles:
  macos:
    dotfiles:
    - f_library_preferences_org.vim.Vim_vimrc
    - f_zshenv
    - f_library_preferences_org.dystroy.broot_conf.toml
    - f_library_preferences_net.sourceforge.zsh.zsh_zshrc
    - f_library_preferences_net.sourceforge.zsh.zsh_joeys-avit.zsh-theme
    - f_library_preferences_re.deadc0de.dotdrop_config.yaml
    - f_library_preferences_net.sourceforge.zsh.zsh_zprofile
    - f_library_preferences_com.npmjs.npm_npmrc
    - f_library_preferences_python_startup
  nixos:
    dotfiles:
    - f_config_vim_vimrc
    - f_config_broot_conf.toml
    - f_config_dotdrop_config.yaml
    - f_config_zsh_themes_joeys-avit.zsh-theme
    - f_etc_nixos_configuration.nix
    - f_config_nixpkgs_config.nix
    - f_etc_nixos_joeyt_default.nix
    - f_etc_nixos_joeyt_z-lua.nix
    - f_etc_nixos_joeyt_zsh.nix
    - f_config_ripgreprc
    - f_config_micro_settings.json
