actions:
  pre:
    # None of these work becuase $ZSH_CUTOM isn't exported as an environment variable
    install-zsh-z: git clone https://github.com/agkozak/zsh-z {{@@ env['ZSH'] @@}}/custom/plugins/zsh-z
    install-you-should-use: git clone https://github.com/MichaelAquilina/zsh-you-should-use.git
      {{@@ env['ZSH'] @@}}/custom/plugins/you-should-use
    install-zsh-autosuggestions: git clone https://github.com/zsh-users/zsh-autosuggestions
      {{@@ env['ZSH'] @@}}/custom/plugins/zsh-autosuggestions
    install-zsh-history-substring-search: git clone https://github.com/zsh-users/zsh-history-substring-search
      {{@@ env['ZSH'] @@}}/custom/plugins/zsh-history-substring-search
    install-zsh-syntax-highlighting: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
      {{@@ env['ZSH'] @@}}/custom/plugins/zsh-syntax-highlighting
config:
  backup: true
  banner: false
  create: true
  dotpath: ~/Projects/config-files
  keepdot: false
  longkey: true
dotfiles:
  f_library_preferences_org.vim.Vim_vimrc:
    src: Library/Preferences/org.vim.Vim/vimrc
    dst: ~/Library/Preferences/org.vim.Vim/vimrc
  f_config_vim_vimrc:
    src: Library/Preferences/org.vim.Vim/vimrc
    dst: ~/.config/vim/vimrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_library_preferences_net.sourceforge.zsh.Zsh:
    src: Library/Preferences/net.sourceforge.zsh.Zsh
    dst: ~/Library/Preferences/net.sourceforge.zsh.Zsh
    instignore:
    - '*/.zsh_history'
    - '*/.zcompdump*'
    - '*/.oh-my-zsh/.editorconfig'
    - '*/.oh-my-zsh/.git/'
    - '*/.oh-my-zsh/.github/'
    - '*/.oh-my-zsh/.gitignore'
    - '*/.oh-my-zsh/CODE_OF_CONDUCT.md'
    - '*/.oh-my-zsh/CONTRIBUTING.md'
    - '*/.oh-my-zsh/LICENSE.txt'
    - '*/.oh-my-zsh/README.md'
    - '*/.oh-my-zsh/cache/'
    - '*/.oh-my-zsh/lib/'
    - '*/.oh-my-zsh/log/'
    - '*/.oh-my-zsh/oh-my-zsh.sh'
    - '*/.oh-my-zsh/plugins/'
    - '*/.oh-my-zsh/templates/'
    - '*/.oh-my-zsh/themes/'
    - '*/.oh-my-zsh/tools/'
    cmpignore:
    - '*/.zsh_history'
    - '*/.zcompdump*'
    - '*/.oh-my-zsh/.editorconfig'
    - '*/.oh-my-zsh/.git/*'
    - '*/.oh-my-zsh/.github/*'
    - '*/.oh-my-zsh/.gitignore'
    - '*/.oh-my-zsh/CODE_OF_CONDUCT.md'
    - '*/.oh-my-zsh/CONTRIBUTING.md'
    - '*/.oh-my-zsh/LICENSE.txt'
    - '*/.oh-my-zsh/README.md'
    - '*/.oh-my-zsh/cache/*'
    - '*/.oh-my-zsh/lib/*'
    - '*/.oh-my-zsh/log/*'
    - '*/.oh-my-zsh/oh-my-zsh.sh'
    - '*/.oh-my-zsh/plugins/*'
    - '*/.oh-my-zsh/templates/*'
    - '*/.oh-my-zsh/themes/*'
    - '*/.oh-my-zsh/tools/*'
    upignore:
    - '*/.zsh_history'
    - '*/.zcompdump*'
    actions:
    - install-zsh-z
    - install-you-should-use
    - install-zsh-autosuggestions
    - install-zsh-history-substring-search
    - install-zsh-syntax-highlighting
  f_library_preferences_re.deadc0de.dotdrop_config.yaml:
    src: Library/Preferences/re.deadc0de.dotdrop/config.yaml
    dst: ~/Library/Preferences/re.deadc0de.dotdrop/config.yaml
  f_config_dotdrop_config.yaml:
    src: Library/Preferences/re.deadc0de.dotdrop/config.yaml
    dst: ~/.config/dotdrop/config.yaml
  f_library_preferences_org.dystroy.broot_conf.toml:
    src: Library/Preferences/org.dystroy.broot/conf.toml
    dst: ~/Library/Preferences/org.dystroy.broot/conf.toml
  f_config_broot_conf.toml:
    src: Library/Preferences/org.dystroy.broot/conf.toml
    dst: ~/.config/broot/conf.toml
  f_etc_nixos_configuration.nix:
    src: etc/nixos/configuration.nix
    dst: /etc/nixos/configuration.nix
    link: nolink
  f_config_nixpkgs_config.nix:
    src: config/nixpkgs/config.nix
    dst: ~/.config/nixpkgs/config.nix
  f_etc_nixos_joeyt_default.nix:
    src: etc/nixos/joeyt/default.nix
    dst: /etc/nixos/joeyt/default.nix
  f_etc_nixos_joeyt_z-lua.nix:
    src: etc/nixos/joeyt/z-lua.nix
    dst: /etc/nixos/joeyt/z-lua.nix
  f_etc_nixos_joeyt_zsh.nix:
    src: etc/nixos/joeyt/zsh.nix
    dst: /etc/nixos/joeyt/zsh.nix
profiles:
  macos:
    dotfiles:
    - f_library_preferences_org.vim.Vim_vimrc
    - f_zshenv
    - d_library_preferences_net.sourceforge.zsh.Zsh
    - f_library_preferences_re.deadc0de.dotdrop_config.yaml
    - f_library_preferences_org.dystroy.broot_conf.toml
  nixos:
    dotfiles:
    - f_config_vim_vimrc
    - f_config_broot_conf.toml
    - f_config_dotdrop_config.yaml
    - f_etc_nixos_configuration.nix
    - f_config_nixpkgs_config.nix
    - f_etc_nixos_joeyt_default.nix
    - f_etc_nixos_joeyt_z-lua.nix
    - f_etc_nixos_joeyt_zsh.nix
