config:
  backup: true
  banner: false
  create: true
  dotpath: . 
  workdir: templated 
  keepdot: false
  link_on_import: link
  cmpignore:
  - '*/.DS_Store'
  upignore:
  - '*/.DS_Store'
  instignore:
  - '*/.DS_Store'
dynvariables:
  os: uname
actions:
  zshenv: ln -s {{ dst }}/.zshenv $HOME/.zshenv
dotfiles:
  f_vimrc:
    src: org.vim.Vim/vimrc
    dst: >-
      {{@@
        '~/.config/vim/vimrc' if env['XDG_CONFIG_HOME'] is string
        else '~/Library/Application Support/org.vim.Vim/vimrc' if os == 'Darwin'
        else '~/.vimrc'
      @@}}
    link: link
  f_org.dystroy.broot_conf.toml:
    src: org.dystroy.broot/conf.toml
    dst: "{{@@ '~/Library/Preferences/org.dystroy.broot/conf.toml' if os == 'Darwin' else '~/.config/broot/conf.toml' @@}}"
    link: link
  f_nixpkgs_config.nix:
    src: org.nixos.Nix/config.nix
    dst: ~/.config/nixpkgs/config.nix
  f_micro_settings.json:
    src: io.github.micro-editor/settings.json 
    dst: ~/.config/micro/settings.json
  f_npmrc:
    src: com.npmjs.Npm/npmrc 
    dst: ~/Library/Application Support/com.npmjs.Npm/npmrc
    link: link
  f_joeys-avit.zsh-theme:
    src: net.sourceforge.Zsh/joeys-avit.zsh-theme
    dst: >-
      {{@@
        '~/.config/zsh/themes/joeys-avit.zsh-theme' if env['XDG_CONFIG_HOME'] is string
        else '~/Library/Application Support/net.sourceforge.Zsh/joeys-avit.zsh-theme' if os == 'Darwin'
        else '~/.zsh/joeys-avit.zsh-theme' 
      @@}}
    link: link
  d_zdotdir:
    src: net.sourceforge.Zsh
    dst: >-
      {{@@
        '~/.config/zsh' if env['XDG_CONFIG_HOME'] is string
        else '~/Library/Application Support/net.sourceforge.Zsh' if os == 'Darwin'
        else '~/.zsh'
      @@}}
    link: link_children
    instignore:
    - joeys-avit.zsh-theme
    - '*/.zshenv'
    cmpignore:
    - joeys-avit.zsh-theme
    - '*/.zshenv'
    - .zcompdump*
    - .zsh_history
    - .zshdb_hist
    - bookmarks
    - zgen*
    - z.txt
    upignore:
    - joeys-avit.zsh-theme
    - '*/.zshenv'
    - .zcompdump*
    - .zsh_history
    - .zshdb_hist
    - bookmarks
    - zgen*
    - z.txt
    actions:
      - zshenv
  f_ripgreprc:
    src: com.github.burntsushi.Ripgrep/ripgreprc
    dst: "{{@@ env['RIPGREP_CONFIG_PATH'] @@}}"
    link: link
profiles:
  macos:
    dotfiles:
    - f_org.dystroy.broot_conf.toml
    - f_vimrc
    - f_npmrc
    - d_zdotdir
    - f_joeys-avit.zsh-theme
    - f_ripgreprc
  nixos:
    dotfiles:
    - f_vimrc
    - f_org.dystroy.broot_conf.toml
    - f_joeys-avit.zsh-theme
    - f_nixpkgs_config.nix
    - f_micro_settings.json
    - f_ripgreprc
