uservariables:
  git_email: Git email
config:
  backup: true
  banner: false
  create: false
  dotpath: org.nixos.Nix
  link_dotfile_default: nolink
  template_dotfile_default: false
  cmpignore:
  - '*/README.md'
  instignore:
  - '*/README.md'
  import_variables:
  - uservariables.yaml:optional
dotfiles:
  d_etc_nixos:
    src: .
    dst: /etc/nixos
    template: true
    instignore:
    - '*/config.nix'
    - '*/darwin-configuration.nix'
    cmpignore:
    - '*/config.nix'
    - '*/darwin-configuration.nix'
    upignore:
    - '*/config.nix'
    - '*/configuration.nix'
profiles:
  nixos:
    dotfiles:
    - d_etc_nixos
