uservariables:
  git_email: Git email
config:
  backup: true
  banner: false
  create: true
  dotpath: .
  workdir: templated
  keepdot: false
  link_on_import: absolute
  link_dotfile_default: absolute
  template_dotfile_default: false
  cmpignore:
  - '*/.DS_Store'
  - '*.swp'
  upignore:
  - '*/.DS_Store'
  - '*.swp'
  instignore:
  - '*/.DS_Store'
  - '*.swp'
  filter_file:
  - re.deadc0de.dotdrop/filters.py
  import_variables:
  - uservariables.yaml:optional
  minversion: 1.13.0
variables:
  vimdir: >-
    {{@@
      '~/Library/Application Support/org.vim.Vim' if profile == 'macos'
      else env['XDG_CONFIG_HOME'] + '/vim' if env['XDG_CONFIG_HOME'] is string
      else '~/.config/vim' if exists('~/.config/vim')
      else '~/.vim'
    @@}}
  broot_config_path: >-
    {{@@
      '~/Library/Application Support/org.dystroy.broot/conf.toml' if profile == 'macos'
      else '~/.config/broot/conf.toml'
    @@}}
  zdotdir: >-
    {{@@
      '~/Library/Application Support/net.sourceforge.Zsh' if profile == 'macos'
      else env['XDG_CONFIG_HOME'] + '/zsh' if env['XDG_CONFIG_HOME'] is string
      else '~/.zsh'
    @@}}
  ripgrep_config_path: >-
    {{@@
      env['RIPGREP_CONFIG_PATH'] if env['RIPGREP_CONFIG_PATH'] is string
      else '~/Library/Application Support/com.github.burntsushi.Ripgrep/ripgreprc'
    if profile == 'macos'
      else env['XDG_CONFIG_HOME'] + '/ripgreprc' if env['XDG_CONFIG_HOME'] is string
      else '~/.config/ripgreprc'
    @@}}
  gitconfig_config_path: >-
    {{@@
      '~/.gitconfig' if profile == 'macos'
      else env['XDG_CONFIG_HOME'] + '/git/config' if env['XDG_CONFIG_HOME'] is string
      else '~/.config/git/config'
    @@}}
  tmux_config_path: >-
    {{@@
      env['XDG_CONFIG_HOME'] + '/tmux/tmux.conf' if env['XDG_CONFIG_HOME'] is string
      else '~/.tmux.conf'
    @@}}
  default_cargo_crates_path: >-
    {{@@
      '~/Library/Application Support/com.asdf-vm.Asdf/.default-cargo-crates' if profile == 'macos'
      else env['XDG_CONFIG_HOME'] + '/asdf-rust/.default-cargo-crates' if env['XDG_CONFIG_HOME'] is string
      else '~/.config/asdf-rust/.default-cargo-crates'
    @@}}
  default_python_packages_path: >-
    {{@@
      '~/Library/Application Support/com.asdf-vm.Asdf/.default-python-packages' if profile == 'macos'
      else env['XDG_CONFIG_HOME'] + '/asdf-python/.default-python-packages' if env['XDG_CONFIG_HOME'] is string
      else '~/.config/asdf-python/.default-python-packages'
    @@}}
dynvariables:
  bat_config_path: command -v bat >/dev/null && bat --config-file || echo $HOME/.bat-not-installed
  editor_exe: command -v vim >/dev/null && which vim || which nano
  bat_exe: command -v bat >/dev/null && which bat || echo -n
  touch_exe: which touch
  ql_exe: '[ "$(uname)" = Darwin ] && command -v ql || echo -n'
  markdown_exe: command -v markdown >/dev/null && which markdown || command -v glow
    || printf ''
actions:
  zshenv: ln -i -s {{@@ _dotfile_abs_dst @@}}/.zshenv ~/.zshenv
dotfiles:
  d_vim:
    src: org.vim.Vim
    dst: '{{@@ vimdir @@}}'
    link: link_children
    template: true
    upignore:
    - '*/.netrwhist*'
    - '*/backup'
    - '*/bundle'
    - '*/coc'
    - '*/swap'
    - '*/undo'
    - '*/viminfo'
    - '*/view'
    - '*/pack'
    - '*/README.md'
    cmpignore:
    - '*/.netrwhist*'
    - '*/backup'
    - '*/bundle'
    - '*/coc'
    - '*/swap'
    - '*/undo'
    - '*/viminfo'
    - '*/view'
    - '*/pack'
    - '*/README.md'
    instignore:
    - '*/README.md'
  f_coc_settings.json:
    src: org.vim.Vim/coc-settings.json
    dst: ~/.config/coc/coc-settings.json
  f_org.dystroy.broot_conf.toml:
    src: org.dystroy.broot/conf.toml
    dst: '{{@@ broot_config_path @@}}'
    template: true
  f_nixpkgs_config.nix:
    src: org.nixos.Nix/config.nix
    dst: ~/.config/nixpkgs/config.nix
  f_micro_settings.json:
    src: io.github.micro-editor/settings.json
    dst: ~/.config/micro/settings.json
  f_npmrc:
    src: com.npmjs.Npm/npmrc
    dst: ~/Library/Application Support/com.npmjs.Npm/npmrc
  d_zdotdir:
    src: net.sourceforge.Zsh/omz
    dst: '{{@@ zdotdir @@}}'
    link: link_children
    template: true
    cmpignore:
    - .zcompdump*
    - .zsh_history
    - .zsh_sessions
    - .zshdb_hist
    - ignored-users.zsh*
    # See comments in .gitignore regarding these next two ignore patterns
    - zfunc/_*
    - bookmarks
    - zgen*
    - z.txt
    - '*/README.md'
    upignore:
    - .zcompdump*
    - .zsh_history
    - .zsh_sessions
    - .zshdb_hist
    - ignored-users.zsh*
    - bookmarks
    - zgen*
    - z.txt
    - '*/README.md'
    instignore:
    - '*/README.md'
    - '*/zfunc/_*'
    actions:
    - zshenv
  d_zdotdir_minimal:
    src: net.sourceforge.Zsh/minimal
    dst: '{{@@ zdotdir @@}}'
    link: link_children
    template: true
    cmpignore:
    - .zcompdump*
    - .zsh_history
    - .zsh_sessions
    - .zshdb_hist
    - ignored-users.zsh*
    - zfunc/_*
    - bookmarks
    - zgen*
    - z.txt
    - '*/README.md'
    upignore:
    - .zcompdump*
    - .zsh_history
    - .zsh_sessions
    - .zshdb_hist
    - ignored-users.zsh*
    - bookmarks
    - zgen*
    - z.txt
    - '*/README.md'
    instignore:
    - '*/README.md'
    - '*/zfunc/_*'
    actions:
    - zshenv
  f_joeys_avit.zsh-theme:
    src: net.sourceforge.Zsh/omz/joeys-avit.zsh-theme
    dst: '{{@@ zdotdir @@}}/themes/joeys-avit.zsh-theme'
    template: true
  f_ripgreprc:
    src: com.github.burntsushi.Ripgrep/ripgreprc
    dst: '{{@@ ripgrep_config_path @@}}'
  f_bat_config:
    src: com.github.sharkdp.Bat/config
    dst: "{{@@ '~/Library/Application Support/bat/config' if profile == 'macos' else
      bat_config_path @@}}"
  f_git_config:
    src: com.git-scm.Git/config
    dst: '{{@@ gitconfig_config_path @@}}'
    template: true
  f_virtualenv.ini:
    src: io.pypa.virtualenv/virtualenv.ini
    dst: ~/Library/Application Support/virtualenv/virtualenv.ini
  f_tmux.conf:
    src: io.github.tmux/tmux.conf
    dst: '{{@@ tmux_config_path @@}}'
    chmod: '600'
    template: true
  f_default-cargo-crates:
    src: com.asdf-vm.Asdf/default-cargo-crates
    dst: '{{@@ default_cargo_crates_path @@}}'
  f_default-python-packages:
    src: com.asdf-vm.Asdf/default-python-packages
    dst: '{{@@ default_python_packages_path @@}}'
profiles:
  macos:
    dotfiles:
    - f_org.dystroy.broot_conf.toml
    - d_vim
    - f_npmrc
    - d_zdotdir
    - f_ripgreprc
    - f_bat_config
    - f_git_config
    - f_virtualenv.ini
    - f_default-cargo-crates
    - f_default-python-packages
  linux:
    dotfiles:
    - d_vim
    - f_ripgreprc
    - f_org.dystroy.broot_conf.toml
    - d_zdotdir_minimal
    - f_bat_config
    - f_git_config
    - f_tmux.conf
    - f_default-cargo-crates
    - f_default-python-packages
  nixos:
    dotfiles:
    - f_org.dystroy.broot_conf.toml
    - f_joeys_avit.zsh-theme
    - f_coc_settings.json
