uservariables:
  git_email: Git email
config:
  backup: true
  banner: false
  dotpath: org.nixos.Nix
  link_dotfile_default: nolink
  template_dotfile_default: false
  cmpignore:
  - '*/README.md'
  instignore:
  - '*/README.md'
  filter_file:
  - re.deadc0de.dotdrop/filters.py
  import_actions:
  - re.deadc0de.dotdrop/actions.yaml
  import_variables:
  - uservariables.yaml:optional
variables:
  state_version: 23.11
dotfiles:
  d_etc_nixos:
    src: .
    dst: /etc/nixos
    template: true
    instignore:
    - '*/config.nix'
    - '*/*-configuration.nix'
    - '!*/hardware-configuration.nix'
    - '*/joeyt/tmux.nix'
    cmpignore:
    - '*/config.nix'
    - '*/*-configuration.nix'
    - '!*/hardware-configuration.nix'
    - '*/joeyt/tmux.nix'
    upignore:
    - '*/config.nix'
    - '*/*-configuration.nix'
    - '!*/hardware-configuration.nix'
    - '*/joeyt/tmux.nix'
    actions:
    - nixfmt
profiles:
  nixos:
    dotfiles:
    - d_etc_nixos
