config:
  backup: true
  banner: false
  create: true
  dotpath: . 
  workdir: templated 
  keepdot: false
  link_on_import: link
  cmpignore:
  - '*/.DS_Store'
  upignore:
  - '*/.DS_Store'
  instignore:
  - '*/.DS_Store'
variables:
  vimdir: >-
    {{@@
      env['XDG_CONFIG_HOME'] + '/vim' if env['XDG_CONFIG_HOME'] is string
      else env['HOME'] + '/Library/Application Support/org.vim.Vim' if profile == 'macos'
      else env['HOME'] + '/.config/vim' if exists('~/.config/vim')
      else env['HOME'] + '/.vim'
    @@}}
dynvariables:
  os: uname
actions:
  zshenv: >-
    ln -i -s "{{@@ _dotfile_abs_dst @@}}/.zshenv" {{@@ env['HOME'] @@}}/.zshenv
  install_vim_plugins: |-
    if [ ! -d "{{@@ vimdir @@}}/pack/vendor/start/nerdtree" ]; then
      # The NERDTree plugin is not installed, so install it
      echo Installing NERDTree Vim plugin
      mkdir -pv {{@@ vimdir @@}}/pack/vendor/start
      git clone https://github.com/preservim/nerdtree.git "{{@@ vimdir @@}}/pack/vendor/start/nerdtree"
      vim -u NONE -c "helptags {{@@ vimdir @@}}/pack/vendor/start/nerdtree/doc" -c q
      echo Installed NERDTree Vim plugin
    else
      echo NERDTree Vim plugin already installed!
    fi
    if [ ! -d "{{@@ vimdir @@}}/pack/vendor/start/nerdtree-git-plugin" ]; then
      # The NERDTree-Git plugin is not installed, so install it
      echo Installing NERDTree Git Plugin Vim plugin
      mkdir -pv {{@@ vimdir @@}}/pack/vendor/start
      git clone https://github.com/Xuyuanp/nerdtree-git-plugin.git "{{@@ vimdir @@}}/pack/vendor/start/nerdtree-git-plugin"
      echo Installed NERDTree Git Plugin Vim plugin
    else
      echo NERDTree Git Plugin Vim plugin already installed!
    fi
    if [ ! -d "{{@@ vimdir @@}}/pack/airblade/start/vim-gitgutter" ]; then
      # The Vim-Gitgutter plugin is not installed, so install it
      echo Installing Vim-Gitgutter Vim plugin
      mkdir -pv {{@@ vimdir @@}}/pack/airblade/start
      git clone https://github.com/airblade/vim-gitgutter.git "{{@@ vimdir @@}}/pack/airblade/start/vim-gitgutter"
      vim -u NONE -c "helptags {{@@ vimdir @@}}/pack/vendor/start/vim-gitgutter/doc" -c q
      echo Installed Vim-Gitgutter Vim plugin
    else
      echo Vim-Gitgutter Vim plugin already installed!
    fi
dotfiles:
  f_vimrc:
    src: org.vim.Vim/vimrc
    dst: "{{@@ '~/.vimrc' if vimdir == '~/.vim' else vimdir + '/vimrc' @@}}"
    link: link
    actions:
    - install_vim_plugins
  f_org.dystroy.broot_conf.toml:
    src: org.dystroy.broot/conf.toml
    dst: "{{@@ '~/Library/Preferences/org.dystroy.broot/conf.toml' if os == 'Darwin' else '~/.config/broot/conf.toml' @@}}"
    link: link
  f_nixpkgs_config.nix:
    src: org.nixos.Nix/config.nix
    dst: ~/.config/nixpkgs/config.nix
  f_micro_settings.json:
    src: io.github.micro-editor/settings.json 
    dst: ~/.config/micro/settings.json
  f_npmrc:
    src: com.npmjs.Npm/npmrc 
    dst: ~/Library/Application Support/com.npmjs.Npm/npmrc
    link: link
  d_zdotdir:
    src: net.sourceforge.Zsh
    dst: >-
      {{@@
        env['XDG_CONFIG_HOME'] + '/zsh' if env['XDG_CONFIG_HOME'] is string
        else '~/Library/Application Support/net.sourceforge.Zsh' if os == 'Darwin'
        else '~/.zsh'
      @@}}
    link: link_children
    cmpignore:
    - .zcompdump*
    - .zsh_history
    - .zshdb_hist
    - bookmarks
    - zgen*
    - z.txt
    upignore:
    - .zcompdump*
    - .zsh_history
    - .zshdb_hist
    - bookmarks
    - zgen*
    - z.txt
    actions:
      - zshenv
  f_ripgreprc:
    src: com.github.burntsushi.Ripgrep/ripgreprc
    dst: "{{@@ env['RIPGREP_CONFIG_PATH'] @@}}"
    link: link
profiles:
  macos:
    dotfiles:
    - f_org.dystroy.broot_conf.toml
    - f_vimrc
    - f_npmrc
    - d_zdotdir
    - f_ripgreprc
  nixos:
    dotfiles:
    - f_vimrc
    - f_org.dystroy.broot_conf.toml
    - f_nixpkgs_config.nix
    - f_micro_settings.json
    - f_ripgreprc
