config:
  backup: true
  banner: false
  create: true
  dotpath: . 
  workdir: templated 
  keepdot: false
  link_on_import: link
  cmpignore:
  - '*/.DS_Store'
  upignore:
  - '*/.DS_Store'
  instignore:
  - '*/.DS_Store'
  func_file:
  - 're.deadc0de.dotdrop/funcs.py'
dynvariables:
  os: uname
actions:
  zshenv: >-
    ln -i -s "{{@@ _dotfile_abs_dst @@}}/.zshenv" {{@@ env['HOME'] @@}}/.zshenv
dotfiles:
  d_vim:
    src: org.vim.Vim
    dst: >-
      {{@@
        env['XDG_CONFIG_HOME'] + '/vim' if env['XDG_CONFIG_HOME'] is string
        else env['HOME'] + '/Library/Application Support/org.vim.Vim' if profile == 'macos'
        else env['HOME'] + '/.config/vim' if exists('~/.config/vim')
        else env['HOME'] + '/.vim'
      @@}}
    link: link_children
    upignore:
    - .netrwhist*
    - backup
    - swap
    - undo
    - viminfo
    cmpignore:
    - .netrwhist*
    - backup
    - swap
    - undo
    - viminfo
    - pack
  f_org.dystroy.broot_conf.toml:
    src: org.dystroy.broot/conf.toml
    dst: "{{@@ '~/Library/Preferences/org.dystroy.broot/conf.toml' if os == 'Darwin' else '~/.config/broot/conf.toml' @@}}"
    link: link
  f_nixpkgs_config.nix:
    src: org.nixos.Nix/config.nix
    dst: ~/.config/nixpkgs/config.nix
  f_micro_settings.json:
    src: io.github.micro-editor/settings.json 
    dst: ~/.config/micro/settings.json
  f_npmrc:
    src: com.npmjs.Npm/npmrc 
    dst: ~/Library/Application Support/com.npmjs.Npm/npmrc
    link: link
  d_zdotdir:
    src: net.sourceforge.Zsh
    dst: >-
      {{@@
        env['XDG_CONFIG_HOME'] + '/zsh' if env['XDG_CONFIG_HOME'] is string
        else '~/Library/Application Support/net.sourceforge.Zsh' if os == 'Darwin'
        else '~/.zsh'
      @@}}
    link: link_children
    cmpignore:
    - .zcompdump*
    - .zsh_history
    - .zshdb_hist
    - bookmarks
    - zgen*
    - z.txt
    upignore:
    - .zcompdump*
    - .zsh_history
    - .zshdb_hist
    - bookmarks
    - zgen*
    - z.txt
    actions:
      - zshenv
  f_ripgreprc:
    src: com.github.burntsushi.Ripgrep/ripgreprc
    dst: "{{@@ env['RIPGREP_CONFIG_PATH'] @@}}"
    link: link
profiles:
  macos:
    dotfiles:
    - f_org.dystroy.broot_conf.toml
    - d_vim
    - f_npmrc
    - d_zdotdir
    - f_ripgreprc
  nixos:
    dotfiles:
    - d_vim
    - f_org.dystroy.broot_conf.toml
